// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZtVyPAFMWupF3sAaVgI_6Z3hdx2Jg9_U',
    appId: '1:364115023121:web:3e1ca0f141b958f34c68b0',
    messagingSenderId: '364115023121',
    projectId: 'swiss-knife-1d3a3',
    authDomain: 'swiss-knife-1d3a3.firebaseapp.com',
    storageBucket: 'swiss-knife-1d3a3.appspot.com',
    measurementId: 'G-ZQGV3VHGGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiyD4z6cT6jAWmBaqVeQ49oeu76Xhtprg',
    appId: '1:364115023121:android:0d9e81061d9961bf4c68b0',
    messagingSenderId: '364115023121',
    projectId: 'swiss-knife-1d3a3',
    storageBucket: 'swiss-knife-1d3a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAESIECDnt7T3RXTv2-snfl_N0mkS5tEGc',
    appId: '1:364115023121:ios:8f3c7994e8f2062a4c68b0',
    messagingSenderId: '364115023121',
    projectId: 'swiss-knife-1d3a3',
    storageBucket: 'swiss-knife-1d3a3.appspot.com',
    iosClientId: '364115023121-cgds34ss8h6uo7d5as732lp0962jbdb2.apps.googleusercontent.com',
    iosBundleId: 'com.example.swissKnife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAESIECDnt7T3RXTv2-snfl_N0mkS5tEGc',
    appId: '1:364115023121:ios:8f3c7994e8f2062a4c68b0',
    messagingSenderId: '364115023121',
    projectId: 'swiss-knife-1d3a3',
    storageBucket: 'swiss-knife-1d3a3.appspot.com',
    iosClientId: '364115023121-cgds34ss8h6uo7d5as732lp0962jbdb2.apps.googleusercontent.com',
    iosBundleId: 'com.example.swissKnife',
  );
}
